services:
  postgres_ticketing:
    image: postgres:18.1
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: ticketing
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_ticketing_data:/var/lib/postgresql
    networks:
      - keycloak-network
  postgres_keycloak:
    image: postgres:18.1
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_PORT: "5432"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres_keycloak
    networks:
      - keycloak-network
volumes:
  postgres_keycloak_data:
  postgres_ticketing_data:
networks:
  keycloak-network:
    driver: bridge